Bump download-artifact action
to hopefully fix the error:

```
 Preparing to download the following artifacts:
- kairos-alpine-3.19.iso.zip (ID: 1164540479, Size: 1053840217)
Redirecting to blob download url: https://productionresultssa4.blob.core.windows.net/actions-results/e30c4747-a895-4fc2-a9ad-5c3c721fbe5c/workflow-job-run-54b5a70f-2f08-532f-96ed-a371e24f143d/artifacts/kairos-alpine-3.19.iso.zip.zip
Starting download of artifact to: /runner/_work/kairos/kairos
(node:1192) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: Unable to download artifact(s): Unable to download and extract artifact: Artifact download failed after 5 retries.
```

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>