Pin setup-buildx-action to v3
because using `master` will eventually fail. Currently fails on master
with:

```
Error: ERROR: failed to initialize builder builder-5c8f04e0-e3af-417d-b07d-2b1a81886763 (builder-5c8f04e0-e3af-417d-b07d-2b1a818867630): Error response from daemon: client version 1.52 is too new. Maximum supported API version is 1.43
```

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>