Add upgrade uki test (#2776)
* [WIP] Add upgrade uki test

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

* Avoid hardcoding single entry

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

* Fix sed

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

* Remove irrelevant option

because otherwise we get this error:

Error: overlay-iso is only supported for iso artifacts

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

* Don't use earthly to build the upgrade image

because the target needs to be adapted to accept a local dir and it's a
mess in Earthly

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

* Fix image name

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

* Add TODO to test

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

* Temporarily change to kairos-agent dev branch

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

* Implement TODO

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

* Use new flag

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

* Add quotes to sed

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

* Make quotes optional

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

* Fix problem with special characters

coming from the transfer of the text over ssh.

`out` had special characters like ^F and ^A in it.

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

* Remove dev branch (we have the fix on master now)

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

* Make the test work also on Alpine

because the device there appears as /dev/dm-0

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

---------

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>